services:
  - name: realdoc-app
    type: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://realdoc-api.onrender.com
