services:
  - type: web
    name: realdoc-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-render-backend-url.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://your-render-backend-url.onrender.com
