services:
  - name: realdoc-app
    type: static
    buildCommand: npm install -D webpack-cli && npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://realdoc-api.onrender.com
