services:
  - type: web
    name: realdoc-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s dist --single
    envVars:
      - key: REACT_APP_API_URL
        value: https://realdoc-api.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://realdoc-api.onrender.com
    routes:
      - src: /(.*)
        dest: /index.html
        status: 200
    headers:
      - key: Cache-Control
        value: no-cache
